name: Run `solhint` linter

on:
  merge_group:
  pull_request:
  push:
    branches:
      - main
      - release/**
    tags:
      - "*"

jobs:
  cache:
    name: Cache the PR number, if available
    uses: ./.github/workflows/reusable-pr-number-cache.yml
    with:
      commit-hash: ${{ github.event.pull_request.head.sha || github.event.after || github.sha }}
      pr-number: ${{ github.event.pull_request.number || 0 }}

  lint:
    # delay the job until the cache job is completed, so that the
    # status can be commented on the PR.
    needs: cache
    strategy:
      fail-fast: true

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install Solhint
        run: npm install --save-dev solhint

      - name: Run Solhint
        run: |
          npx solhint 'src/**/*.sol' -c ./src/.solhint.json
