name: Slither Analysis

on:
  merge_group:
  pull_request:
  push:
    branches:
      - main
      - release/**
    tags:
      - "*"

jobs:
  cache:
    name: Cache the PR number, if available
    uses: ./.github/workflows/reusable-pr-number-cache.yml
    with:
      commit-hash: ${{ github.event.pull_request.head.sha || github.event.after || github.sha }}
      pr-number: ${{ github.event.pull_request.number || 0 }}

  analyze:
    # delay the job until the cache job is completed, so that the
    # status can be commented on the PR.
    needs: cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crytic/slither-action@v0.4.0
        with:
          fail-on: medium